version: BuildNr.{build}

image: Visual Studio 2022

shallow_clone: true

clone_folder: c:\projects\game.libretro

environment:
  app_id: game.libretro

  matrix:
    - GENERATOR: "Visual Studio 17 2022"
      ARCHITECTURE: Win32
      CONFIGURATION: Release
      CMAKE_DEFINES: -DCMAKE_SYSTEM_NAME=Windows -DCMAKE_SYSTEM_VERSION="10.0.22000.0"
    - GENERATOR: "Visual Studio 17 2022"
      ARCHITECTURE: x64
      CONFIGURATION: Release
      CMAKE_DEFINES: -DCMAKE_SYSTEM_NAME=Windows -DCMAKE_SYSTEM_VERSION="10.0.22000.0"
    # Disabled until VS bug is fixed
    #- GENERATOR: "Visual Studio 17 2022"
    #  ARCHITECTURE: x64
    #  CONFIGURATION: Release
    #  CMAKE_DEFINES: -DCMAKE_SYSTEM_NAME=WindowsStore -DCMAKE_SYSTEM_VERSION="10.0.22000.0"
    #- GENERATOR: "Visual Studio 17 2022"
    #  ARCHITECTURE: ARM64
    #  CONFIGURATION: Release
    #  CMAKE_DEFINES: -DCMAKE_SYSTEM_NAME=WindowsStore -DCMAKE_SYSTEM_VERSION="10.0.22000.0"

build_script:
  - cd ..
  - git clone --branch retroplayer-20.3 --depth=1 https://github.com/garbear/xbmc.git
  - cd %app_id%
  - mkdir build
  - cd build
  - mkdir -p definition\%app_id%
  - echo %app_id% %APPVEYOR_BUILD_FOLDER% %APPVEYOR_REPO_COMMIT% > definition\%app_id%\%app_id%.txt
  - cmake -T host=x64 -G "%GENERATOR%" -A %ARCHITECTURE% %CMAKE_DEFINES% -DADDONS_TO_BUILD=%app_id% -DCMAKE_BUILD_TYPE=%CONFIGURATION% -DADDONS_DEFINITION_DIR=%APPVEYOR_BUILD_FOLDER%/build/definition -DADDON_SRC_PREFIX=../.. -DCMAKE_INSTALL_PREFIX=../../xbmc/addons -DPACKAGE_ZIP=1 ../../xbmc/cmake/addons
  - cmake --build . --config %CONFIGURATION% --target %app_id%
